### PR TITLE
make backbutton work

### PR DESCRIPTION
**Pull request by 00aitoni**
Code still needs cleanup

### CODE REVIEW

**Comment by 00aitoni** [comment]
Q. Why did you use VideoSettingsActivity instead of ReVancedSettingsActivity?
A. To use the back button toolbar, we must define a completely new activity.

And to use a new activity, `activity` must be declared in `AndroidManifest.xml`.

However, since the new activity declaration is not reflected in the ROOT version, in the past TeamVanced adopted a method of overriding `LicenseActivity` with another method.
(They renamed `XSettingsFragment` to `LicenseActivity`, then override it)
https://discord.com/channels/952946952348270622/953965039105232906/990620263215411250

However, since there is no way to override the existing smali file on the current method, the method used by TeamVanced could not be adopted as it is.
In the end, the workaround currently used by the ReVanced Team was adopted.

The workaround I've found is:
- An activity is declared in `AndroidManifest.xml`, but you need to find an activity that does not exist on smali.
(`LicenseActivity` also has an activity declared in AndroidManifest.xml, but it already exists on smali.)

The activity that satisfies this is `VideoQualitySettingsActivity`.

Therefore, I renamed `ReVancedSettingsActivity` to `VideoQualitySettingsActivity`.

**Comment by 0xrxL** [comment]
Heh...too many changes and too many lines of code moved from a place to another. Honestly I don't know if this will be accepted by oSum.

Maybe before open a new PR I should show this to him.

**Comment by 0xrxL** [comment]
Obviously I'm referring to the integrations changes.

**Comment by 0xrxL** [comment]
https://github.com/revanced/revanced-patches/issues/1384

**Pull request merged**
